#ifndef DEFS_HPP_
#define DEFS_HPP_

#define WINDOW_WIDTH 1280
#define WINDOW_HEIGHT 960

#define BOARD_WIDTH_BOUNDRY WINDOW_WIDTH - 50
#define BOARD_HEIGHT_BOUNDRY WINDOW_HEIGHT - 135

#define MAX_FRAME_TIME 0.25F
#define PILL_GRAVITY_VELOCITY 0.0001F
#define PILL_MOVEMENT_VELOCITY 0.125F
#define DT 0.01F

#endif
